"""Error code constants for darling-express backend."""

# Auth
AUTH_INVALID_PHONE = "AUTH_INVALID_PHONE"
AUTH_PHONE_NOT_FOUND = "AUTH_PHONE_NOT_FOUND"
AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"

# Catalog
CATALOG_PRODUCT_NOT_FOUND = "CATALOG_PRODUCT_NOT_FOUND"
CATALOG_OUT_OF_STOCK = "CATALOG_OUT_OF_STOCK"

# Orders
ORDER_NOT_FOUND = "ORDER_NOT_FOUND"
ORDER_ALREADY_PAID = "ORDER_ALREADY_PAID"
ORDER_INVALID_STATE = "ORDER_INVALID_STATE"
ORDER_INSUFFICIENT_STOCK = "ORDER_INSUFFICIENT_STOCK"

# Shipping
SHIPPING_UNAVAILABLE = "SHIPPING_UNAVAILABLE"
SHIPPING_QUOTE_FAILED = "SHIPPING_QUOTE_FAILED"

# Payments
PAYMENT_CHARGE_FAILED = "PAYMENT_CHARGE_FAILED"
PAYMENT_WEBHOOK_INVALID_SIGNATURE = "PAYMENT_WEBHOOK_INVALID_SIGNATURE"

# Generic
VALIDATION_ERROR = "VALIDATION_ERROR"
INTERNAL_ERROR = "INTERNAL_ERROR"
PERMISSION_DENIED = "PERMISSION_DENIED"
NOT_FOUND = "NOT_FOUND"
