# Generated by Django 5.0.8 on 2026-05-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED_PREPARING', 'Approved / Preparing'), ('IN_TRANSIT', 'In transit'), ('DELIVERED', 'Delivered'), ('CANCELED', 'Canceled'), ('SHIPPING_UNAVAILABLE', 'Shipping unavailable')], db_index=True, default='PENDING', max_length=32)),
                ('payment_method', models.CharField(choices=[('PIX_INFINITEPAY', 'PIX InfinitePay'), ('MANUAL', 'Manual')], default='PIX_INFINITEPAY', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('infinitepay_transaction_id', models.CharField(blank=True, max_length=128)),
                ('lalamove_order_id', models.CharField(blank=True, max_length=128)),
                ('lalamove_tracking_url', models.URLField(blank=True)),
                ('dispatch_request_id', models.CharField(blank=True, max_length=128)),
                ('dispatch_retry_count', models.PositiveIntegerField(default=0)),
                ('dispatch_last_error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('INFINITEPAY', 'InfinitePay')], max_length=20)),
                ('provider_event_id', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('IGNORED_DUPLICATE', 'Ignored duplicate'), ('FAILED', 'Failed')], default='RECEIVED', max_length=20)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
