# Generated by Django 5.0.8 on 2026-05-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payments_enabled', models.BooleanField(default=False)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default='150.00', max_digits=10)),
                ('lalamove_api_key', models.CharField(blank=True, max_length=512)),
                ('infinitepay_api_key', models.CharField(blank=True, max_length=512)),
                ('store_lat', models.FloatField(blank=True, null=True)),
                ('store_lng', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'system settings',
                'verbose_name_plural': 'system settings',
            },
        ),
    ]
